// Generated by Claude
const remToPx = () => ({
  postcssPlugin: "rem-to-px",
  Declaration(decl) {
    if (decl.value.includes("rem")) {
      decl.value = decl.value.replace(
        /(-?\d*\.?\d+)rem/g,
        (_, n) => `${+(parseFloat(n) * 18).toFixed(3)}px`,
      );
    }
  },
});
remToPx.postcss = true;

export default {
  plugins: [(await import("@tailwindcss/postcss")).default(), remToPx()],
};
